var HSK2Object = { 
	"hsk2":[
	    { "character":"吧", "pinyin":"ba", "definition":"modal particle indicating polite  suggestion; ...right?;...OK?" },
	    { "character":"白", "pinyin":"bái","definition":"white; snowy;" },
	    { "character":"百", "pinyin":"bǎi" ,"definition":"hundred; numerous; all kinds of;" },
	    { "character":"帮助", "pinyin":"bāng zhù" ,"definition":"assistance; aid; to help; to assist", "mnemonic":"a nation(邦) full of turbans(巾) about to(且) show their power(力)..." },
	    { "character":"报纸", "pinyin":"bào zhǐ" ,"definition":"newspaper; " },
	    { "character":"比", "pinyin":"bǐ" ,"definition":"particle used for comparison and '-er than'; to compare; " },
	    { "character":"别", "pinyin":"bié" ,"definition":"do not; must not;" },
	    { "character":"宾馆", "pinyin":"bīn guǎn" ,"definition":"guesthouse;" },
	    { "character":"长", "pinyin":"cháng" ,"definition":"long; length" },
	    { "character":"唱歌", "pinyin":"chàng gē" ,"definition":"to sing a song", "mnemonic":"口 = mouth; 昌 = light of sun, good; 日 = sun; 哥 = elder brother 'gē'" },
	    { "character":"出", "pinyin":"chū" ,"definition":"go out, send out; stand; produce" },
	    { "character":"穿", "pinyin":"chuān" ,"definition":"to wear;" },
	    { "character":"次", "pinyin":"cì" ,"definition":"next in sequence; second; the second (day, time etc); secondary; " },
	    { "character":"从", "pinyin":"cóng" ,"definition":"from; via; passing through; through" },
	    { "character":"错", "pinyin":"cuò" ,"definition":"mistake; wrong", "mnemonic":"where 昔 formerly had been 钅money..." },
	    { "character":"打篮球", "pinyin":"dǎ lán qiú" ,"definition":"play basketball", "mnemonic":"扌hand 丁 male adult..." },
	    { "character":"大家", "pinyin":"dà jiā" ,"definition":"everyone" },
	    { "character":"到", "pinyin":"dào" ,"definition":"to (a place); until (a time); up to; to go; to arrive" },
	    { "character":"得", "pinyin":"de" ,"definition":"structural particle: used after a verb (or adjective as main verb), linking it to following phrase indicating effect, degree, possibility etc;" },
	    { "character":"等", "pinyin":"děng" ,"definition":"class / rank / grade", "mnemonic" : "寺 means 'temple', 竹 means 'bamboo', a monk from a bamboo temple is of the hightest rank!"},
	    { "character":"弟弟", "pinyin":"dì di" ,"definition":"younger brother;", "mnemonic":"弔 means 'pity; hang', a younger brother is hanging from mom's arms, with little ears on top"},
	    { "character":"第一", "pinyin":"Dì yī" ,"definition":"first; number one", "mnemonic" : "第 means 'sequence, number; grade, degree'" },
	    { "character":"懂", "pinyin":"dǒng" ,"definition":"to understand; to know", "mnemonic":"忄means 'heart', 董 means 'to supervise', knowledge supervises the heart" },
	    { "character":"对", "pinyin":"duì" ,"definition":"right; correct" },
	    { "character":"房间", "pinyin":"fáng jiān" ,"definition":"room;", "mnemonic":"House room. 戸 door in a 方 square = 房 house"},
	    { "character":"非常", "pinyin":"fēi cháng" ,"definition":"extraordinary; unusual; extreme; very; exceptional", "mnemonic":"非 not/opposite 常 normal" },
	    { "character":"服务员", "pinyin":"fú wù yuán" ,"definition":"waiter;" },
	    { "character":"高", "pinyin":"gāo" ,"definition":"high; tall" },
	    { "character":"告诉", "pinyin":"gàosù" ,"definition":"to tell; to inform; to let know" },
	    { "character":"哥哥", "pinyin":"gē ge" ,"definition":"older brother;" },
	    { "character":"给", "pinyin":"gěi" ,"definition":"to (someone); for; (to give) to", "mnemonic":"纟= silk, 合 = join." },
	    { "character":"公共汽车", "pinyin":"gōng gòng qì chē" ,"definition":"bus;" },
	    { "character":"公司", "pinyin":"gōng sī" ,"definition":"(business) company; company;" },
	    { "character":"贵", "pinyin":"guì" ,"definition":"expensive; noble; your (name); precious" },
	    { "character":"过", "pinyin":"Guò" ,"definition":"(used after a verb) to indicate the completion of an action" },
	    { "character":"孩子", "pinyin":"hái zi" ,"definition":"child" },
	    { "character":"还", "pinyin":"hái" ,"definition":"still; yet; even more; still more; also; too; as well" },
	    { "character":"好吃", "pinyin":"hǎo chī" ,"definition":"tasty; delicious" },
	    { "character":"黑", "pinyin":"hēi" ,"definition":"black;" },
	    { "character":"红", "pinyin":"hóng" ,"definition":"red;" },
	    { "character":"火车站", "pinyin":"huǒ chē zhàn" ,"definition":"train station" },
	    { "character":"机场", "pinyin":"jī chǎng" ,"definition":"airport; airfield;" },
	    { "character":"鸡蛋", "pinyin":"jī dàn" ,"definition":"(chicken) egg; " },
	    { "character":"件", "pinyin":"jiàn" ,"definition":"item; component; classifier for events, things, clothes etc", "mnemonic":"亻or 人 means 'man'. 牛 = cow" },
	    { "character":"教室", "pinyin":"jiào shì" ,"definition":"classroom;" },
	    { "character":"姐姐", "pinyin":"jiě jie" ,"definition":"older sister;", "mnemonic":"	女 = 'woman' that 且 = 'about to, will soon' marry." },
	    { "character":"介绍", "pinyin":"jiè shào" ,"definition":"to present; to introduce;", "mnemonic":"介 forerunner + 绍 join" },
	    { "character":"近", "pinyin":"jìn" ,"definition":"near; close to; approximately" },
	    { "character":"进", "pinyin":"jìn" ,"definition":"to enter; to advance;" },
	    { "character":"就", "pinyin":"jiù" ,"definition":"just (emphasis); at once; right away; only; as early as; already;" },
	    { "character":"觉得", "pinyin":"jué de" ,"definition":"to think; to feel" },
	    { "character":"咖啡", "pinyin":"kā fēi" ,"definition":"coffee;" },
	    { "character":"开始", "pinyin":"kāi shǐ" ,"definition":"to begin" },
	    { "character":"考试", "pinyin":"kǎo shì" ,"definition":"exam;" },
	    { "character":"可能", "pinyin":"kě néng" ,"definition":"maybe" },
	    { "character":"可以", "pinyin":"kě yǐ" ,"definition":"can; may; possible; able to" },
	    { "character":"课", "pinyin":"kè" ,"definition":"subject; course; class; lesson;", "mnemonic":"讠= speech; 果 = fruit, result;" },
	    { "character":"快", "pinyin":"kuài" ,"definition":"rapid; quick;" },
	    { "character":"快乐", "pinyin":"kuài lè" ,"definition":"happy; merry" },
	    { "character":"累", "pinyin":"lèi" ,"definition":"tired;", "mnemonic":"I want to lay my head in a 糸 silk 田 field" },
	    { "character":"离", "pinyin":"lí" ,"definition":"to leave; to part from; to be away from; (in giving distances) from; ", "mnemonic":"㐫 cruel, unfortunate, sad. 禸 rump. 'she 㐫 cruely turned her 禸 back to me'" },
	    { "character":"两", "pinyin":"liǎng" ,"definition":"two (quantities); both;" },
	    { "character":"零", "pinyin":"líng" ,"definition":"zero; nought; " },
	    { "character":"路", "pinyin":"lù" ,"definition":"road; path; way; ", "mnemonic":"足 foot, 各 all" },
	    { "character":"旅游", "pinyin":"lǚyóu" ,"definition":"trip; journey; tourism; travel; tour", "mnemmonic":"trip + to tour. 方 square/region, 㫃 flags flying, 氏 family" },
	    { "character":"卖", "pinyin":"mài" ,"definition":"to sell; to betray;" },
	    { "character":"慢", "pinyin":"màn" ,"definition":"slow", "mnemonic":"忄= heart; 曼 = long; 日 = sun; 罒 = net; 又 = and, also" },
	    { "character":"忙", "pinyin":"máng" ,"definition":"busy; hurriedly", "mnemonic":"亡 = death, destroyed; lose, perish; When you're busy, your heart is slowly dying :o" },
	    { "character":"每", "pinyin":"měi" ,"definition":"each; every" },
	    { "character":"妹妹", "pinyin":"mèi mei" ,"definition":"younger sister; " },
	    { "character":"门", "pinyin":"mén" ,"definition":"gate; " },
	    { "character":"面条", "pinyin":"miàn tiáo" ,"definition":"noodles" },
	    { "character":"男", "pinyin":"nán" ,"definition":"male; ", "mnemonic":"men use their 力 power to work on the 田 field"},
	    { "character":"您", "pinyin":"nín" ,"definition":"you (polite); " },
	    { "character":"牛奶", "pinyin":"niú nǎi" ,"definition":"cow's milk; " },
	    { "character":"女", "pinyin":"nǚ" ,"definition":"female; woman; daughter;" },
	    { "character":"旁边", "pinyin":"Pángbiān" ,"definition":"lateral; side; to the side; beside" },
	    { "character":"跑步", "pinyin":"pǎo bù" ,"definition":"to walk quickly; to march; to run" },
	    { "character":"便宜", "pinyin":"pián yi" ,"definition":"cheap; inexpensive; small advantages; to let sb off lightly" },
	    { "character":"票", "pinyin":"piào" ,"definition":"ticket;" },
	    { "character":"妻子", "pinyin":"qī zi" ,"definition":"wife;" },
	    { "character":"起床", "pinyin":"qǐ chuáng" ,"definition":"to get up" },
	    { "character":"千", "pinyin":"qiān" ,"definition":"thousand" },
	    { "character":"铅笔", "pinyin":"qiān bǐ" ,"definition":"(lead) pencil;" },
	    { "character":"晴", "pinyin":"qíng" ,"definition":"clear; fine (weather)" },
	    { "character":"去年", "pinyin":"qù nián" ,"definition":"last year" },
	    { "character":"让", "pinyin":"ràng" ,"definition":"to permit; to let sb do sth; to have sb do sthto yield", "mnemonic":"讠speech/words, 上 top/superior" },
	    { "character":"日", "pinyin":"rì" ,"definition":"day; day of the month; date; sun; abbr. for 日本 Japan" },
	    { "character":"上班", "pinyin":"shàng bān" ,"definition":"to go to work; to be on duty; to start work; to go to the office" },
	    { "character":"身体", "pinyin":"shēn tǐ" ,"definition":"(human) body; health;" },
	    { "character":"生病", "pinyin":"shēng bìng" ,"definition":"to fall ill; to sicken" },
	    { "character":"生日", "pinyin":"shēng rì" ,"definition":"birthday;" },
	    { "character":"时间", "pinyin":"shí jiān" ,"definition":"time; period; " },
	    { "character":"事情", "pinyin":"Shìqíng" ,"definition":"affair; matter; thing; business" },
	    { "character":"手表", "pinyin":"shǒu biǎo" ,"definition":"wrist watch;" },
	    { "character":"手机", "pinyin":"shǒu jī" ,"definition":"cell phone; cellular phone; mobile phone;", "mnemonic":"hand machine" },
	    { "character":"说话", "pinyin":"shuō huà" ,"definition":"to speak; to say" },
	    { "character":"送", "pinyin":"sòng" ,"definition":"to deliver; to carry; to give (as a present); to present (with); to see off; to send", "mnemonic":"辶 means 'walk', 关 means 'relation', you give a present to move the relation along!" },
	    { "character":"虽然…但是…", "pinyin":"suī rán …dàn shì …" ,"definition":"although…still…; even if…nevertheless..." },
	    { "character":"它", "pinyin":"tā" ,"definition":"it (inanimate thing or animal)" },
	    { "character":"踢足球", "pinyin":"tī zú qiú" ,"definition":"play soccer (football)" },
	    { "character":"题", "pinyin":"tí" ,"definition":"topic; problem for discussion;" },
	    { "character":"跳舞", "pinyin":"tiào wǔ" ,"definition":"to dance", "mnemonic":"跳 means 'to jump', and 舞 'to dance', 舛 means to oppose (dance partners?)"},
	    { "character":"外", "pinyin":"wài" ,"definition":"outside; in addition; foreign; external", "mnemonic":"a foreigner was fortune telling(卜) in the night(夕), outside" },
	    { "character":"完", "pinyin":"wán" ,"definition":"to finish; to be over; whole; complete; entire" },
	    { "character":"玩", "pinyin":"wán" ,"definition":"to play;", "mnemonic":"a king(王) plays with dollars(元 also means head.. XD)"},
	    { "character":"晚上", "pinyin":"wǎn shang" ,"definition":"in the evening;", "mnemonic":"when the sun(日) is evading(免 evade), it is night(晚)" },
	    { "character":"往", "pinyin":"wǎng" ,"definition":"to go (in a direction); to; " , "mnemonic":"彳means 'to step with left foot'"},
	    { "character":"为什么", "pinyin":"wèi shén me" ,"definition":"for what reason?; why?" },
	    { "character":"问", "pinyin":"wèn" ,"definition":"to ask" },
	    { "character":"问题", "pinyin":"wèn tí" ,"definition":"question; problem; issue; topic;" },
	    { "character":"希望", "pinyin":"xī wàng" ,"definition":"to wish for; to desire; hope", "mnemonic":"希 means 'to hope', and 望 means 'to look at, look forward; to hope, expect'" },
	    { "character":"西瓜", "pinyin":"xī guā" ,"definition":"watermelon; " },
	    { "character":"洗", "pinyin":"xǐ" ,"definition":"to wash; to bathe", "mnemonic":"wash with 氵water to return to your 先 former self" },
	    { "character":"小时", "pinyin":"xiǎo shí" ,"definition":"hour;" },
	    { "character":"笑", "pinyin":"xiào" ,"definition":"laugh; smile; " },
	    { "character":"新", "pinyin":"xīn" ,"definition":"new; newly" },
	    { "character":"姓", "pinyin":"xìng" ,"definition":"family name; surname; name; " },
	    { "character":"休息", "pinyin":"xiūxí" ,"definition":"rest; to rest" },
	    { "character":"雪", "pinyin":"xuě" ,"definition":"snow;" },
	    { "character":"颜色", "pinyin":"yán sè" ,"definition":"color;", "mnemonic":"颜 = appearance, 色 = color, 彡 = hair, 产 = produce, 页 = page, sheet"},
	    { "character":"眼睛", "pinyin":"Yǎnjīng" ,"definition":"eye;" },
	    { "character":"羊肉", "pinyin":"yáng ròu" ,"definition":"mutton" },
	    { "character":"药", "pinyin":"yào" ,"definition":"medicine; drug; cure;" },
	    { "character":"要", "pinyin":"yào" ,"definition":"to want; will; going to" },
	    { "character":"也", "pinyin":"yě" ,"definition":"also; too;" },
	    { "character":"一下", "pinyin":"yī xià" ,"definition":"one time; once;" },
	    { "character":"已经", "pinyin":"yǐ jīng" ,"definition":"already" },
	    { "character":"一起", "pinyin":"yī qǐ" ,"definition":"together" },
	    { "character":"意思", "pinyin":"yì si" ,"definition":"idea; opinion; meaning; wish; desire;" },
	    { "character":"因为…所以…", "pinyin":"yīn wèi …suǒ yǐ …" ,"definition":"because… thus…; on account of…then…" },
	    { "character":"阴", "pinyin":"yīn" ,"definition":"overcast (weather); cloudy; shady; Yin (the negative principle of Yin and Yang)", "mnemonic":"there's always a 阝place on the 月 moon in the shade" },
	    { "character":"游泳", "pinyin":"yóu yǒng" ,"definition":"swim" },
	    { "character":"右边", "pinyin":"yòu bian" ,"definition":"right side; right, to the right" },
	    { "character":"鱼", "pinyin":"yú" ,"definition":"fish;" },
	    { "character":"远", "pinyin":"yuǎn" ,"definition":"far; distant; remote" },
	    { "character":"运动", "pinyin":"yùn dòng" ,"definition":"movement; campaign; sports;" },
	    { "character":"再", "pinyin":"zài" ,"definition":"again" },
	    { "character":"早上", "pinyin":"zǎo shang" ,"definition":"early morning; Good morning!;" },
	    { "character":"丈夫", "pinyin":"Zhàngfū" ,"definition":"husband;" },
	    { "character":"找", "pinyin":"zhǎo" ,"definition":"to try to find; to look for;" },
	    { "character":"着", "pinyin":"zhe" ,"definition":"particle attached after verb to indicate action in progress, like -ing ending" },
	    { "character":"真", "pinyin":"zhēn" ,"definition":"really; truly" },
	    { "character":"正在", "pinyin":"zhèng zài" ,"definition":"in the process of (doing something or happening); while (doing)" },
	    { "character":"知道", "pinyin":"zhī dào" ,"definition":"to know; to be aware of" },
	    { "character":"准备", "pinyin":"zhǔn bèi" ,"definition":"preparation; prepare" },
	    { "character":"走", "pinyin":"zǒu" ,"definition":"to walk; to go; to run;" },
	    { "character":"最", "pinyin":"zuì" ,"definition":"most; the most; -est" },
	    { "character":"左边", "pinyin":"zuǒ bian" ,"definition":"left; the left side; to the left of" },
	],
}